


[[d1_databases]]
binding = "squareblocksdb" # available in your Worker on env.DB
database_name = "squareblocksdb"
database_id = "3cf11196-05cb-4276-9bbd-ead735f36c9f"

[[r2_buckets]]
binding = "squareblocks"
bucket_name = "squareblocks"

kv_namespaces = [
  { binding = "SquaresKV", id = "758bea6a1d9a4c4688d1db73af49bdc6" }
]


[vars]
baseUrl = "https://squares.town"
rpcUrl =  "https://rpc.blast.io"
squaresContractAddress = "0x2933f1a981b40409a26864284fD8169e5DA159c8"
stateContractAddress = "0x119E95F4deBdFdaE96D07E1239255847742F1cA3"

STATE_CONTRACT_ABI = """
[
  {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "stateId",
          "type": "uint256"
        }
      ],
      "name": "getStateSquares",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
]
"""
projectName="Squares Town"
graphUrl="https://api.studio.thegraph.com/proxy/48884/squareblocks/version/latest"
PIXEL_SERVICE_URL="https://ipfs.squares.town/pixelService/"
compatibility_flags = ["nodejs_compat"]
