


[[d1_databases]]
binding = "squareblocksdb" # available in your Worker on env.DB
database_name = "squareblocksdb"
database_id = "3cf11196-05cb-4276-9bbd-ead735f36c9f"

[[r2_buckets]]
binding = "squareblocksr2"
bucket_name = "squareblocksr2"

kv_namespaces = [
  { binding = "SquaresKV", id = "758bea6a1d9a4c4688d1db73af49bdc6" }
]


[vars]
baseUrl = "https://squares.town"
rpcUrl =  "https://polygon-mainnet.infura.io/v3/615e0266e5284aeeb5863c6731dbf11e"
stateContractAddress = "0x26721AfAc4E8a508BBa7086556048Cb47289Fd85"
squaresContractAddress = "0x24d46cE4aC42b4103a18dFd7F7467311e7Cc95d1"
STATE_CONTRACT_ABI = """
[
  {
      "inputs": [
        {
          "internalType": "uint256",
          "name": "stateId",
          "type": "uint256"
        }
      ],
      "name": "getStateSquares",
      "outputs": [
        {
          "internalType": "uint256[]",
          "name": "",
          "type": "uint256[]"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
]
"""
projectName="Squares Town"
graphUrl="https://api.studio.thegraph.com/proxy/48884/squareblocks/version/latest"
PIXEL_SERVICE_URL="https://pixelservice.squares.town"
compatibility_flags = ["nodejs_compat"]
