name = "transactionparser"
type = "javascript" # Or "webpack" if you're using that



[[d1_databases]]
binding = "squareblocksdb" # available in your Worker on env.DB
database_name = "squareblocksdb"
database_id = "3cf11196-05cb-4276-9bbd-ead735f36c9f"

[[r2_buckets]]
binding = "squareblocksr2"
bucket_name = "squareblocksr2"

kv_namespaces = [
  { binding = "SquaresKV", id = "758bea6a1d9a4c4688d1db73af49bdc6" }
]


[vars]
baseUrl = "https://squares.town"
rpcUrl =  "https://polygon-mainnet.infura.io/v3/615e0266e5284aeeb5863c6731dbf11e"
stateContractAddress = "0x34a36B7a1Ea11F91A24E9439A4877496a8522d73"
squaresContractAddress = "0xC1eDaF7DD7A82B754b51F826bf57E227D1327957"
STATE_CONTRACT_ABI = """
[
  {
    "constant": true,
    "inputs": [{"name": "stateId", "type": "uint256"}],
    "name": "getStateSquares",
    "outputs": [{"name": "", "type": "uint256[]"}],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  }
]
"""
projectName="Squares Town"
graphUrl="https://api.studio.thegraph.com/proxy/48884/squareblocks/version/latest"
PIXEL_SERVICE_URL="https://pixelservice.vercel.app"
compatibility_flags = ["nodejs_compat"]
